[server]
maxUploadSize = 500
enableXsrfProtection = false
enableCORS = false
headless = true
port = 8501

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[runner]
fastReruns = true
magicEnabled = true

[client]
showErrorDetails = true
toolbarMode = "minimal"